### PR TITLE
#52 add about us page

### PR DESCRIPTION
**Pull request by hassanuahmad**
@JagrajAulakh please review

### CODE REVIEW

**Comment by JagrajAulakh** [comment]
Is there a reason for moving `InvestInYourFuture.js` out of `CoursePage/` @hassanuahmad ?

**Comment by hassanuahmad** [comment]
> Is there a reason for moving `InvestInYourFuture.js` out of `CoursePage/` @hassanuahmad ?

**Comment by hassanuahmad** [comment]
because we will be using that component at the end of mostly every page so there was no point recreating it everytime we create a page

**Comment by hassanuahmad** [comment]
I am using it in the about us page and all the course pages and hopefully in the application process page as well

**Review by JagrajAulakh — APPROVED** [review]
Time to make it responsive now
pedro-pascal-mandalorian

**Pull request merged**
